export const authors = [
  'Roman Serebryakov',
  'Dmitry Durach',
  'Alex Belous',
  'Denis Sheremetov',
  'Nikolay Makarevich',
  'Sergey Holin',
  'Vitaliy Erep',
  'Maxim Kamenschikov',
  'Vladimir Gordienko',
  'Denys Buhor',
  'Ivan Spishniak',
  'Serhii Popesku',
  'Nikolay Puzyr',
  'Valeriy Checha',
];